name: Test and Deploy

on:
  push:
    branches: -main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55word

      - name: Test Utils and App
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55word npm test
