name: Test & Deploy

on:
  push:
    branches:
      - ncnews-actions

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_news_test
          postgresql user: mr_testerson
          postgresql password: pa55word

      - name: Test Utils and App
        run: PGDATABASE=nc_news_test PGUSER=mr_testerson PGPASSWORD=pa55word npm test
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout and clone repo
  #       uses: actions/checkout@v2
  #     - name: Deploy to Heroku
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #        with:
  #          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
  #          heroku_email: ${{secrets.HEROKU_EMAIL}}
